import type { CropDef, CropId } from './types';

// Starting values; balanced in Phase 11.
export const CROPS: Readonly<Record<CropId, CropDef>> = {
  // Likes warm and humid; sensitive to cold and low water.
  cucumber: {
    name: 'Cucumber',
    growthDays: 20,
    yieldPerPlot: 14,
    basePrice: 1.0,
    climate: {
      temperature: {
        limitLow: 12,
        optimalLow: 22,
        optimalHigh: 28,
        limitHigh: 38,
        growthWeight: 1.5,
        stressBelow: 2,
        stressAbove: 0.75,
      },
      humidity: {
        limitLow: 45,
        optimalLow: 70,
        optimalHigh: 85,
        limitHigh: 98,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
      co2: {
        limitLow: 150,
        optimalLow: 600,
        optimalHigh: 1000,
        limitHigh: 2000,
        growthWeight: 0.75,
        stressBelow: 0.2,
        stressAbove: 0.5,
      },
      light: {
        limitLow: 50,
        optimalLow: 300,
        optimalHigh: 800,
        limitHigh: 1500,
        growthWeight: 1,
        stressBelow: 0.5,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 30,
        optimalLow: 60,
        optimalHigh: 85,
        limitHigh: 98,
        growthWeight: 1.5,
        stressBelow: 2,
        stressAbove: 0.5,
      },
      nutrients: {
        limitLow: 0.5,
        optimalLow: 1.8,
        optimalHigh: 2.8,
        limitHigh: 5,
        growthWeight: 0.75,
        stressBelow: 1,
        stressAbove: 1,
      },
    },
  },

  // Likes high light and CO2; sensitive to humidity and nutrients.
  tomato: {
    name: 'Tomato',
    growthDays: 30,
    yieldPerPlot: 10,
    basePrice: 1.6,
    climate: {
      temperature: {
        limitLow: 10,
        optimalLow: 18,
        optimalHigh: 26,
        limitHigh: 35,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
      humidity: {
        limitLow: 40,
        optimalLow: 60,
        optimalHigh: 80,
        limitHigh: 95,
        growthWeight: 0.5,
        stressBelow: 1.5,
        stressAbove: 1.5,
      },
      co2: {
        limitLow: 150,
        optimalLow: 700,
        optimalHigh: 1000,
        limitHigh: 2000,
        growthWeight: 1.25,
        stressBelow: 0.2,
        stressAbove: 0.5,
      },
      light: {
        limitLow: 50,
        optimalLow: 500,
        optimalHigh: 1000,
        limitHigh: 1500,
        growthWeight: 1.5,
        stressBelow: 0.5,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 20,
        optimalLow: 50,
        optimalHigh: 75,
        limitHigh: 95,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
      nutrients: {
        limitLow: 0.5,
        optimalLow: 2.5,
        optimalHigh: 3.5,
        limitHigh: 6,
        growthWeight: 1,
        stressBelow: 1.5,
        stressAbove: 1.5,
      },
    },
  },

  // Likes steady warmth; sensitive to cold and low light.
  pepper: {
    name: 'Pepper',
    growthDays: 36,
    yieldPerPlot: 7,
    basePrice: 2.4,
    climate: {
      temperature: {
        limitLow: 12,
        optimalLow: 21,
        optimalHigh: 27,
        limitHigh: 35,
        growthWeight: 1.25,
        stressBelow: 2,
        stressAbove: 0.75,
      },
      humidity: {
        limitLow: 40,
        optimalLow: 60,
        optimalHigh: 75,
        limitHigh: 95,
        growthWeight: 0.5,
        stressBelow: 1,
        stressAbove: 1,
      },
      co2: {
        limitLow: 150,
        optimalLow: 600,
        optimalHigh: 1000,
        limitHigh: 2000,
        growthWeight: 0.75,
        stressBelow: 0.2,
        stressAbove: 0.5,
      },
      light: {
        limitLow: 50,
        optimalLow: 450,
        optimalHigh: 1000,
        limitHigh: 1500,
        growthWeight: 1.25,
        stressBelow: 1.5,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 20,
        optimalLow: 45,
        optimalHigh: 70,
        limitHigh: 95,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
      nutrients: {
        limitLow: 0.5,
        optimalLow: 2.0,
        optimalHigh: 3.0,
        limitHigh: 6,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
    },
  },
};
