import type { CropDef, CropId } from './types';

// Starting values; balanced in Phase 11. Prices are fixed. Growth times are set so that, in the
// starting greenhouse, crops take about 2 min, 7 min, 30 min, 1 h and 2 h of
// real time. Longer crops earn more per harvest but less per hour, so active
// play pays and slow crops suit a break.
export const CROPS: Readonly<Record<CropId, CropDef>> = {
  // Trays of young shoots, cut after a few days. Easy-going; drinks little.
  microgreens: {
    name: 'Microgreens',
    growthHours: 8,
    yieldPerPlot: 6,
    seedCost: 3,
    price: 2,
    waterUse: 0.05,
    shelfLifeDays: 4,
    climate: {
      temperature: {
        limitLow: 10,
        optimalLow: 18,
        optimalHigh: 24,
        limitHigh: 32,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
      humidity: {
        limitLow: 35,
        optimalLow: 50,
        optimalHigh: 80,
        limitHigh: 95,
        growthWeight: 0.75,
        stressBelow: 1,
        stressAbove: 1,
      },
      co2: {
        limitLow: 100,
        optimalLow: 350,
        optimalHigh: 1200,
        limitHigh: 2500,
        growthWeight: 0.5,
        stressBelow: 0.1,
        stressAbove: 0.2,
      },
      light: {
        limitLow: 20,
        optimalLow: 100,
        optimalHigh: 450,
        limitHigh: 1200,
        growthWeight: 0.75,
        stressBelow: 0.5,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 25,
        optimalLow: 55,
        optimalHigh: 85,
        limitHigh: 98,
        growthWeight: 1.5,
        stressBelow: 1.5,
        stressAbove: 0.5,
      },
    },
  },

  // Likes warm and humid; sensitive to cold and low water.
  cucumber: {
    name: 'Cucumber',
    growthHours: 24,
    yieldPerPlot: 14,
    seedCost: 6,
    price: 3.5,
    waterUse: 0.12,
    shelfLifeDays: 8,
    climate: {
      temperature: {
        limitLow: 12,
        optimalLow: 22,
        optimalHigh: 28,
        limitHigh: 38,
        growthWeight: 1.5,
        stressBelow: 2,
        stressAbove: 0.75,
      },
      humidity: {
        limitLow: 45,
        optimalLow: 70,
        optimalHigh: 85,
        limitHigh: 98,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
      co2: {
        limitLow: 150,
        optimalLow: 600,
        optimalHigh: 1000,
        limitHigh: 2000,
        growthWeight: 0.75,
        stressBelow: 0.2,
        stressAbove: 0.5,
      },
      light: {
        limitLow: 50,
        optimalLow: 300,
        optimalHigh: 800,
        limitHigh: 1500,
        growthWeight: 1,
        stressBelow: 0.5,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 30,
        optimalLow: 60,
        optimalHigh: 85,
        limitHigh: 98,
        growthWeight: 1.5,
        stressBelow: 2,
        stressAbove: 0.5,
      },
    },
  },

  // Likes it cool; damp air brings mould, and the berries spoil fast.
  strawberry: {
    name: 'Strawberry',
    growthHours: 112,
    yieldPerPlot: 8,
    seedCost: 15,
    price: 12,
    waterUse: 0.06,
    shelfLifeDays: 3,
    climate: {
      temperature: {
        limitLow: 6,
        optimalLow: 16,
        optimalHigh: 24,
        limitHigh: 32,
        growthWeight: 1.25,
        stressBelow: 1,
        stressAbove: 1.5,
      },
      humidity: {
        limitLow: 40,
        optimalLow: 60,
        optimalHigh: 75,
        limitHigh: 92,
        growthWeight: 1,
        stressBelow: 0.5,
        stressAbove: 2,
      },
      co2: {
        limitLow: 150,
        optimalLow: 600,
        optimalHigh: 1000,
        limitHigh: 2000,
        growthWeight: 0.75,
        stressBelow: 0.2,
        stressAbove: 0.5,
      },
      light: {
        limitLow: 50,
        optimalLow: 300,
        optimalHigh: 700,
        limitHigh: 1400,
        growthWeight: 1.25,
        stressBelow: 0.75,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 25,
        optimalLow: 55,
        optimalHigh: 75,
        limitHigh: 92,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1.5,
      },
    },
  },

  // Likes high light and CO2; sensitive to humidity.
  tomato: {
    name: 'Tomato',
    growthHours: 196,
    yieldPerPlot: 16,
    seedCost: 15,
    price: 9,
    waterUse: 0.04,
    shelfLifeDays: 10,
    climate: {
      temperature: {
        limitLow: 10,
        optimalLow: 18,
        optimalHigh: 26,
        limitHigh: 35,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
      humidity: {
        limitLow: 40,
        optimalLow: 60,
        optimalHigh: 80,
        limitHigh: 95,
        growthWeight: 0.5,
        stressBelow: 1.5,
        stressAbove: 1.5,
      },
      co2: {
        limitLow: 150,
        optimalLow: 700,
        optimalHigh: 1000,
        limitHigh: 2000,
        growthWeight: 1.25,
        stressBelow: 0.2,
        stressAbove: 0.5,
      },
      light: {
        limitLow: 50,
        optimalLow: 500,
        optimalHigh: 1000,
        limitHigh: 1500,
        growthWeight: 1.5,
        stressBelow: 0.5,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 20,
        optimalLow: 50,
        optimalHigh: 75,
        limitHigh: 95,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
    },
  },

  // Likes steady warmth; sensitive to cold and low light.
  pepper: {
    name: 'Pepper',
    growthHours: 425,
    yieldPerPlot: 10,
    seedCost: 30,
    price: 28,
    waterUse: 0.025,
    shelfLifeDays: 14,
    climate: {
      temperature: {
        limitLow: 12,
        optimalLow: 21,
        optimalHigh: 27,
        limitHigh: 35,
        growthWeight: 1.25,
        stressBelow: 2,
        stressAbove: 0.75,
      },
      humidity: {
        limitLow: 40,
        optimalLow: 60,
        optimalHigh: 75,
        limitHigh: 95,
        growthWeight: 0.5,
        stressBelow: 1,
        stressAbove: 1,
      },
      co2: {
        limitLow: 150,
        optimalLow: 600,
        optimalHigh: 1000,
        limitHigh: 2000,
        growthWeight: 0.75,
        stressBelow: 0.2,
        stressAbove: 0.5,
      },
      light: {
        limitLow: 50,
        optimalLow: 450,
        optimalHigh: 1000,
        limitHigh: 1500,
        growthWeight: 1.25,
        stressBelow: 1.5,
        stressAbove: 0.5,
      },
      water: {
        limitLow: 20,
        optimalLow: 45,
        optimalHigh: 70,
        limitHigh: 95,
        growthWeight: 1,
        stressBelow: 1,
        stressAbove: 1,
      },
    },
  },
};
